// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Workboard.Domain.SPEntity
{
    public partial class spRetrieveProjectListResult
    {
        public int ProjectId { get; set; }
        [StringLength(50)]
        public string Name { get; set; } = default!;
        [StringLength(100)]
        public string Description { get; set; } = default!;
        public int CreatedId { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}
