// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Workboard.Domain.SPEntity
{
    public partial class spRetrieveNotificationListResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Message { get; set; } = default!;
        public int UserId { get; set; }
    }
}
