// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Workboard.Domain.SPEntity
{
    public partial class spRetrieveUserListResult
    {
        public int UserId { get; set; }
        [StringLength(50)]
        public string UserName { get; set; } = default!;
        [StringLength(50)]
        public string EmailAddress { get; set; } = default!;
    }
}
