// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Workboard.Domain.SPEntity
{
    public partial class spRetrieveTaskListPerIdResult
    {
        public int TaskId { get; set; }
        [StringLength(50)]
        public string TaskTitle { get; set; } = default!;
        [StringLength(200)]
        public string TaskDescription { get; set; } = default!;
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string Priority { get; set; } = default!;
        [StringLength(50)]
        public string Status { get; set; } = default!;
        public DateTime DueDate { get; set; }
        public int ProjectId { get; set; }
        [StringLength(50)]
        public string MemberAssigned { get; set; } = default!;
    }
}
