// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Workboard.Domain.SPEntity;

namespace Workboard.Infratsructure.Contexts
{
    public partial interface IWorkboard_DBContextProcedures
    {
        Task<List<spRetrieveNotificationListResult>> spRetrieveNotificationListAsync(int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spRetrieveProjectListResult>> spRetrieveProjectListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spRetrieveTaskListResult>> spRetrieveTaskListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spRetrieveTaskListPerIdResult>> spRetrieveTaskListPerIdAsync(int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spRetrieveUserListResult>> spRetrieveUserListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
