// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Workboard.Domain.Entities;

public partial class Comment
{
    public int Id { get; set; }

    public int? TaskId { get; set; }

    public int? UserId { get; set; }

    public string? ContentValue { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Task? Task { get; set; }

    public virtual User? User { get; set; }
}