// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Workboard.Domain.Entities;

public partial class ProjectMember
{
    public int UserId { get; set; }

    public int? ProjectId { get; set; }

    public string? Role { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Project? Project { get; set; }

    public virtual User User { get; set; } = null!;
}